pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["menu_bancos.html","Módulo Administrativo &#62; Menú Bancos","Menú Bancos",""],
["menu_compras.html","Módulos Operativos &#62; Menú Compras","Menú Compras",""],
["menu_consultas_reportes.html","Módulos Operativos &#62; Menú Consultas y Reportes","Menú Consultas y Reportes",""],
["menu_contabilidad.html","Módulo Administrativo &#62; Menú Contabilidad","Menú Contabilidad",""],
["menu_general_administrativo.html","Módulo Administrativo &#62; Menú General","Menú General",""],
["menu_general_operativo.html","Módulos Operativos &#62; Menú General","Menú General",""],
["menu_inventario.html","Módulos Operativos &#62; Menú Inventario","Menú Inventario",""],
["menu_taller.html","Módulos Operativos &#62; Menú Taller","Menú Taller",""],
["menu_ventas.html","Módulos Operativos &#62; Menú Ventas","Menú Ventas",""],
["modulos_operativos.html","Módulos Operativos","Módulos Operativos",""],
["modulo_administrativo.html","Módulo Administrativo","Módulo Administrativo",""],
["newproject20140805_ftsearch.html","No title","Lo Nuevo de la Versión 801.00 Contents | Index | Search Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): ",""],
["otras_mejoras_operativas.html","Módulos Operativos &#62; Otras Mejoras Operativas","Otras Mejoras Operativas",""]];
